apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-postgres-deployment
  labels:
    app: postgres-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
      - name: postgres-product
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-product-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-product-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-product-secret
              key: POSTGRES_PASSWORD
---     
apiVersion: v1
kind: Service
metadata:
  name: product-postgres-service
spec:
  selector:
    app: postgres-product
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432